### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Eashwar93** [Namburger/edgetpu-minimal-example#1]
**System info**

- Ubuntu 18.04
- Edge TPU Compiler version 2.1.302470888
- TENSORFLOW COMMIT = "5d0b55dd4a00c74809e5b32217070a26ac6ef823"

**Issue**
@Namburger 
I'm trying to write an application to do classification of video-stream from the inbuilt camera in my laptop using edgetpu. I have used OpenCV to read, decode and vectorize the input to the model. As a first step I wanted to check the compatilibitty of images decoded by OpenCV with TFlite interpretors. So I have written the following code adapted from minimal.cc. I have not made any changes in **building** the tf interpreter, but the TFlite interpreter doesn't build and I get the following error. I have added a few debug messages to understand where exactly the problem lies nothing else. I could pin point that it is building the interpreter but beyond that I have no idea. The minimal executable runs fine with no issues having the same codes to build the interpreter which is what making me think that I have done something wrong here. Code snippet and error message for your reference. 
The source file is attached [here](https://drive.google.com/file/d/1qNxkOa_XN7_x5DhEeQlz1f3H11Zbuw_w/view?usp=sharing) for your reference.

> std::unique_ptr<tflite::FlatBufferModel> model =
>       tflite::FlatBufferModel::BuildFromFile(model_path.c_str());
>   if (model == nullptr) {
>     std::cerr << "Fail to build FlatBufferModel from file: " << model_path << std::endl;
>     std::abort();
>   }
>   else
> 	  {
>     	std::cout << "model loaded successfully" << std::endl;
> 	  }
> 
>   // Build interpreter.
>   std::shared_ptr<edgetpu::EdgeTpuContext> edgetpu_context =
>       edgetpu::EdgeTpuManager::GetSingleton()->OpenDevice();
> 
>   std::unique_ptr<tflite::Interpreter> interpreter;
>   if (!edgetpu_context) {
>     interpreter = std::move(coral::BuildInterpreter(*model));
>   } else {
>   	std::cout << "opening of edgtpu successful, building interpretor" <<std :: endl;
>     interpreter = std::move(coral::BuildEdgeTpuInterpreter(*model, edgetpu_context.get()));
>   }
>   std::cout << "Interpreter built";

![Screenshot from 2020-05-01 12-34-31](https://user-images.githubusercontent.com/51912916/80799541-647e0080-8ba7-11ea-9dde-6a8e88b9ded0.png)

Would be nice if this issue is resolved
**Edit**
- TENSORFLOW COMMIT =d855adfc5a0195788bf5f92c3c7352e638aa1109

**Comment by Namburger** [comment]
@Eashwar93 
Unfortunately, changing the commit number will not work with `libedgetpu` because the 1 is dependent of the other. The current released version of `libedgetpu` was build on [this commit](https://github.com/Namburger/edgetpu-minimal-example/blob/master/CMakeLists.txt#L12) which is the required commit. All this complexity will soften up as soon as we opensource libedgetpu, at that time you can build both libraries on any commits you want :)

**Comment by Eashwar93** [comment]
@Namburger I'm sorry I just copied the wrong commit number from another post. 
I did not replace the TF repo that comes with this package. It is the same as d855adfc5a0195788bf5f92c3c7352e638aa1109. 

Sorry for the confusion. My bad. In-spite of the correct TF commit the above error persists.

**Comment by Namburger** [comment]
@Eashwar93 I see, I'll take a look, I'll get back with you on this later today!
[edit] Humn, I'm really confused, this is still working for me, did it ever work for you? Could you try adding something like this to see if the tpu can still be recognize?
```
const auto& available_tpus =
      edgetpu::EdgeTpuManager::GetSingleton()->EnumerateEdgeTpu();
auto tpupath = available_tpus[0].path;
cout << tpupath;
```

**Comment by Eashwar93** [comment]
@Namburger Sorry for the delayed response I forgot to check. The TPU is recognized during the runtime. Please refer to the screenshot below:
![Screenshot from 2020-05-05 12-15-20](https://user-images.githubusercontent.com/51912916/81055775-af5e8780-8ec9-11ea-96e5-da47fe5cadfa.png)


Also as I mentioned earlier the minimal executable runs fine. Do you think I would have meesed up my cmake file? Cmake file attached [here](https://drive.google.com/file/d/15wc9D4NXsF6NUtxzqZ5BVgmVdadHrms8/view?usp=sharing) for your reference

[edit]I think I found the issue, will correct it and repost

**Comment by Eashwar93** [comment]
The issue was in casting the variables. I tested the code it works completely fine. if someone is interested in video classification using coral, then you can use this as a reference. apart from edgetpu and tflite libraries you need to have OpenCV installed as well for the code that I have written. Please also modify your Cmake file accordingly. The source code and cmake lists can be found [here ](https://drive.google.com/drive/folders/1COJ3CArnpZ9aHdSOpSxvjg32rODz0Tuh?usp=sharing)for your reference. I will also create a repo soon regarding video tasks in coral in the future and will attach a link here in the upcoming days.

@Namburger a big thanks to you for making our lives easier

**Comment by Namburger** [comment]
@Eashwar93 oops, sorry, I just realized I never responded to you and I just now saw the notification :( Sorry it has been a busy time :)
Very nice, saw that you've also got a hang of cmake, this will come very handy. 
I guess if you want object detection with video stream also, then you can check [this repo](https://github.com/Namburger/edgetpu-detection-camera) 
Cheers
