### ISSUE TITLE
../out/aarch64/minimal doesn't exist

### ISSUE THREAD

**Issue by sammilei** [Namburger/edgetpu-minimal-example#3]
Hi,

Thank for making this repo. I have the issue with running my own tflite model in the Edge-TPU's cpp API.

ERROR: Internal: Unsupported data type in custom op handler: -119671996
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Failed to allocate tensors.

Through a github pose. I followed the instruction in this repo and the building was successful. However, I could not run the example detection. I used `../out/k8/minimal` instead of `../out/aarch64/minimal` because the latter is not found. And the similar error occurred: 

ERROR: Internal: Unsupported data type in custom op handler: 0
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Failed to allocate tensors.
Segmentation fault (core dumped)

Thank you!

**Comment by Namburger** [comment]
@sammilei 
This repo is using an older version of tensorflow, libedgetpu, therefore you need to load that same version during runtime.
Have you done the export LD_LIBRARY_PATH part?

**Comment by sammilei** [comment]
Thanks @Namburger for you quick response!
Yes I did the `export LD_LIBRARY_PATH part`.

**Comment by sammilei** [comment]
Update:
Sorry. I now did the LD_LIBRARY_PATH as `export LD_LIBRARY_PATH=../libedgetpu/direct/k8`

Then the sample detection works
`/edgetpu-minimal-example/build$ ../out/k8/minimal ../test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite ../test_data/resized_cat.bmp ../test_data/imagenet_labels.txt`

Class: tabby, tabby cat
Score: 0.0390625

Class: tiger cat
Score: 0.128906

Class: Siamese cat, Siamese
Score: 0.00390625

Class: Egyptian cat
Score: 0.792969

Class: doormat, welcome mat
Score: 0.0078125

Class: radiator
Score: 0.0078125

Class: space heater
Score: 0.0117188
